#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : R-mvnormtest
Version  : 0.1.9.3
Release  : 41
URL      : https://cran.r-project.org/src/contrib/mvnormtest_0.1-9-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/mvnormtest_0.1-9-3.tar.gz
Summary  : Normality Test for Multivariate Variables
Group    : Development/Tools
License  : GPL-2.0
Requires: R-mvnormtest-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package license
Summary: license components for the R-mvnormtest package.
Group: Default

%description license
license components for the R-mvnormtest package.


%prep
%setup -q -n mvnormtest
pushd ..
cp -a mvnormtest buildavx2
popd
pushd ..
cp -a mvnormtest buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711507954

%install
export SOURCE_DATE_EPOCH=1711507954
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-mvnormtest
cp %{_builddir}/mvnormtest/inst/COPYING %{buildroot}/usr/share/package-licenses/R-mvnormtest/dfac199a7539a404407098a2541b9482279f690d || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mvnormtest/COPYING
/usr/lib64/R/library/mvnormtest/ChangeLog
/usr/lib64/R/library/mvnormtest/DESCRIPTION
/usr/lib64/R/library/mvnormtest/INDEX
/usr/lib64/R/library/mvnormtest/Meta/Rd.rds
/usr/lib64/R/library/mvnormtest/Meta/features.rds
/usr/lib64/R/library/mvnormtest/Meta/hsearch.rds
/usr/lib64/R/library/mvnormtest/Meta/links.rds
/usr/lib64/R/library/mvnormtest/Meta/nsInfo.rds
/usr/lib64/R/library/mvnormtest/Meta/package.rds
/usr/lib64/R/library/mvnormtest/NAMESPACE
/usr/lib64/R/library/mvnormtest/R/mvnormtest
/usr/lib64/R/library/mvnormtest/R/mvnormtest.rdb
/usr/lib64/R/library/mvnormtest/R/mvnormtest.rdx
/usr/lib64/R/library/mvnormtest/help/AnIndex
/usr/lib64/R/library/mvnormtest/help/aliases.rds
/usr/lib64/R/library/mvnormtest/help/mvnormtest.rdb
/usr/lib64/R/library/mvnormtest/help/mvnormtest.rdx
/usr/lib64/R/library/mvnormtest/help/paths.rds
/usr/lib64/R/library/mvnormtest/html/00Index.html
/usr/lib64/R/library/mvnormtest/html/R.css

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-mvnormtest/dfac199a7539a404407098a2541b9482279f690d
